language: fortran

sudo: required

env:
  - FC=mpif77 CC=mpicc

before_install: 
  - export ROOT_DIR=$(pwd -P)

  # Install MPICH
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  # Download Snapshots
  - (cd bin; ./gsnaps)

  # Set up Nek5000
  - git clone --single-branch -b presolve-fix https://github.com/kent0/Nek5000
  - export SOURCE_ROOT=$ROOT_DIR/Nek5000
  - (cd Nek5000/tools; ./maketools genmap)

jobs:
  include:
    - stage: compilation
      script: $ROOT_DIR/tests/comp-baf-test
    -
      script: $ROOT_DIR/tests/comp-bafr-test
    - stage: test
      script: $ROOT_DIR/tests/bafr-test
