language: fortran

sudo: required

env:
  - FC=gfortran CC=gcc MPI=0

before_install: 
  - export ROOT_DIR=`pwd`

  # Install MPICH
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  # Set up Nek5000
  - git clone https://github.com/Nek5000/Nek5000
  - export SOURCE_ROOT=$ROOT_DIR/Nek5000

script: 
  - $ROOT_DIR/tests/comp-baf-test
  - $ROOT_DIR/tests/comp-bafr-test
