dist: xenial

language: bash

notifications:
  email:
    on_success: change
    on_failure: always

sudo: required

addons:
  artifacts:
    s3_region: us-east-2
    paths:
      - "tests/t/fail.log"

before_install:
  - cd bin; source setup; cd -
  - source tests/travis_fn

  # Install MPICH
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  # Install Julia
  - wget -nv https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.3-linux-x86_64.tar.gz
  - tar xvzf julia-1.0.3-linux-x86_64.tar.gz
  - sudo ln -v -s $MOR_DIR/julia-1.0.3/bin/julia /usr/bin/julia
  - $MOR_DIR/tests/julia-init

  # Setup Nek5000
  - git clone --single-branch -b presolve-fix https://github.com/kent0/Nek5000
  - export SOURCE_ROOT=$MOR_DIR/Nek5000
  - (cd Nek5000/tools; ./maketools genmap)

  # Test Julia
  - julia-1.0.3/bin/julia --version
  - /usr/bin/julia --version
  - /usr/bin/env julia --version

  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -m pip install -U pip
  - pip install -U wheel
  - pip install numpy
  - pip install pytest
    #  - python setup.py build
    #  - python -m pytest

before_script:
  - export FC=mpif77
  - export CC=mpicc
  - export FFLAGS="-w -mcmodel=medium -fprofile-arcs -ftest-coverage"
  - export USR_LFLAGS+="-mcmodel=medium"

script: $MOR_DIR/tests/test.sh
jobs:
  include:
  - stage: unit
    env: TYPE=UNIT TEST=GRAMIAN           IPS=L2
  - env: TYPE=UNIT TEST=IC                IPS=L2
  - env: TYPE=UNIT TEST=A0                IPS=L2
  - env: TYPE=UNIT TEST=B0                IPS=L2
  - env: TYPE=UNIT TEST=C0                IPS=L2
  - env: TYPE=UNIT TEST=GRAMIAN           IPS=H10
  - env: TYPE=UNIT TEST=IC                IPS=H10
  - env: TYPE=UNIT TEST=A0                IPS=H10
  - env: TYPE=UNIT TEST=B0                IPS=H10
  - env: TYPE=UNIT TEST=C0                IPS=H10
  - env: TYPE=UNIT TEST=CP                IPS=H10
  - stage: integration
    env: TYPE=INTEG TEST=CYL IPS=L2 NP=1 NB=20 LB=20 SCR=tdragx
  - env: TYPE=INTEG TEST=CYL IPS=L2 NP=2 NB=20 LB=20 SCR=tdragx
  - env: TYPE=INTEG TEST=CYL IPS=L2 NP=1 NB=20 LB=50 SCR=tdragx
  - env: TYPE=INTEG TEST=CYL IPS=L2 NP=1 NB=10 LB=10 SCR=tbox
  - env: TYPE=INTEG TEST=CYL IPS=L2 NP=1 NB=20 LB=20 SCR=tcopt

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
   global:
     - ARTIFACTS_BUCKET=travis-kent0
     - secure: bnXmYvIM+avMEjfHSwJ+VyXppvUSov2cMwagXJgU8xRgTkWhDD1H1lzN+PYqDr66859vzdc+kxxDK17yVfEOqUEiZAeEdWhe+fvXznijPPI8C7Gyycra81XWpxFhGaweOF0q+cUQbjZJhcd4O+aHTVtAVi3QWA1rQsucHrLzjixpW28eooPAQ0x01BZkSmfq6eaJ+2mpby3j6gfHbrz7nmmEa+SaDtuZ9kFZPvrABAJ/W5EetrTUMP2a+X/y4IwrAZhbma+z+uSmsNMf8mgydyar9Nnt9pxjcpOtsMrhBv5nY0ngDGAR0mzJn2ZD/mzwC5xI0PApYhgyIXTdPsGAPhyDjEbzhQqv8UmcuqzFTrtalYekTTAM+6orr3bOaLo/7Uv83+CdiXAh87sRRyMQ9nwNmHAQRWNdXHRLbamoQIBmQcOxZa2Uwspq8RbIlzeshYlSA4P0EK5rgkgAVVw/NohoFOh3f7pNdxhM3iUPGB6s6d885ktOpWWoaMngZjL2wl5KQ9JWjv9I/v4gEI0KcDsQwsasxDBnsBhaFq1Caur4Rd04qXPRMzlG4JH0dYsSvqjJNaXe3XhPXvdou/V7j9+Mlo5ZhfWpLvRHxOX8hz+PXVz0DZ7cDTl0XM0rM26t6T9zuD1pCNRdYMHqJJX4wAqKoKj51cZXfwmhaWby1+c=
     - secure: AmFro8th7hsGh9C3Cnp50fp/z4yc0n0hwPR4ZeA9ISLV4shHzkbxWyhedA/7E/UFgTVfhfeUsicrcKEtU5nlybRA/EsWI/P0H3R570ZRfxPeWOCcPx4gNHwM8rnVhqRySz729ZJB/PrXLojtJYMleZ7TG/iopB0mDUn42s3k8AFCo/xfUTCsAB/FxeyDP8laHr6wIQDDQJw9qfUP/ppwCDItEF3/b5JunNhEyhNPLGaTcgp12qSoT7dAw6naIUYyuZVVYCB1qiiFmCm0MRFXm8Aq6oG5NWoul+BiL5GpRav1pDU/P+kYx4jw1mnZHvDUWer4tBgUO48f0UA+atyUN6zwzuSvZl+2Nx2Ig1x0EIrWzIGBhqB7+EcKIVZOQ7bLYkbWVANLu1+PGfphgbtTPHs4VmTa/5qaogjgv6Y1qKe6NfDIO4T+ektIc6/AYMpEJUbiW/A5G9EozwxSKxCGK0BuTuPxHRR6JGgdEqQVqGETPUnNtehGF3ehAjX321S4DjyK8E0A7Bt8FVXZkz+/61YOGiosVnrHbQd9FGILxj9eEEa02ZgH4ltMoETT6/UqGu1GTNIqBOrqolMkiNI6OaDLNK02WC4dfTsC+x5drWFbBn5ensRoXG5RhEQqETWKoTlyxQsi/EajRmDucKK8geMITf3HGR8Mwb9newRPaP8=
     - secure: vYQxFCOYHAJ7fyZk1LrjSzA0K0OmVyPkQbP0PVjMUT5IY4OZnCuKy20iKnQsx0S9Jf1mK/b/pHojODkCrlNEn4a7v6hyU4cxg3YOixlEiLvV6N9LHAGP2ndg+IS8WUm+ETUcAAWweMfuEdnD6OxDXerZk6ZnKX8ws64X9qaUFTpc12K0FSUSX3KcKbtx7PSdOVOGZ07BdWYZWGfKVq1JJsjA4nD4OyZjUHYJfDSYwz3HMElc2Okh+VLRKHJvP19E9bZ/ETafEFYY2bBPDKPMZSqrHoYOpPzKU4OAy/oQClcJF5FOa7c1nv2gSv/HLG6GC/sSGbZ/UGKwuUTdP7GEPwg4NfzjlUrvNNFzxFytUcuKjqSIfB1KBMZP4SkEqpaErbbFNBcG39Zd99OU8hErRrRmGneuzG/xGZnEA8OIHyG9eUFWOqSxZnXTIAfEG9z4+kwEotfnWoe7Ec0I22PipKl8NQOm6Rm8BHJMnH77LEFabg59yi0pWQeWlGuRugLn9ZbjigJQbkxMSawnnBVAlysuMbK7Pre0wmFpKRbHWIGR7xwNM2e6287G3sch0n7i31baNCa0HhIYQ0PYLVeJoy6/VDiKO50BpB89Pb2noLPV7ayTQGBSwK5hjqTf8MxW+eWv53k0NWLI6Fw8znyIf9WvvoJqvCT5GG6HoaFyP0g=
