language: bash

notifications:
  email:
    on_success: change
    on_failure: always

sudo: required

before_install: 
  - export ROOT_DIR=$(pwd -P)

  # Install MPICH
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  # Set up Nek5000
  - git clone --single-branch -b presolve-fix https://github.com/kent0/Nek5000
  - export SOURCE_ROOT=$ROOT_DIR/Nek5000
  - (cd Nek5000/tools; ./maketools genmap)

before_script:
  - export FC=mpif77
  - export CC=mpicc
  - export FFLAGS="-w -mcmodel=medium"
  - export USR_LFLAGS+="-mcmodel=medium"

script: $ROOT_DIR/tests/test.sh

jobs:
    include:
      - stage: unit
        env: TEST=GRAMMIAN_UNIT
      -
        env: TEST=EIGENVECTOR_UNIT
      -
        env: TEST=BASES_UNIT
      -
        env: TEST=INITIAL_CONDITION_UNIT
      -
        env: TEST=A0_UNIT
      -
        env: TEST=B0_UNIT
      -
        env: TEST=C0_UNIT

#     - stage: integration
#       env: TEST=BAF_INTEG
