dist: xenial

language: bash

notifications:
  email:
    on_success: change
    on_failure: always

sudo: required

addons:
  artifacts:
    s3_region: us-east-2
    paths:
      - "tests/t/fail.log"

before_install:
  - cd bin; source setup; cd -
  - source tests/travis_fn

  # Install MPICH
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  # Install Julia
  - wget -nv https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.3-linux-x86_64.tar.gz
  - tar xvzf julia-1.0.3-linux-x86_64.tar.gz
  - sudo ln -v -s $MOR_DIR/julia-1.0.3/bin/julia /usr/bin/julia
  - $MOR_DIR/tests/julia-init

  # Setup Nek5000
  - git clone --single-branch -b presolve-fix https://github.com/kent0/Nek5000
  - export SOURCE_ROOT=$MOR_DIR/Nek5000
  - (cd Nek5000/tools; ./maketools genmap)

  # Test Julia
  - julia-1.0.3/bin/julia --version
  - /usr/bin/julia --version
  - /usr/bin/env julia --version

  - virtualenv --python=python venv
  - source venv/bin/activate
  - python -m pip install -U pip
  - pip install -U wheel
  - pip install numpy
  - pip install pytest
    #  - python setup.py build
    #  - python -m pytest

before_script:
  - export FC=mpif77
  - export CC=mpicc
  - export FFLAGS="-w -mcmodel=medium -fprofile-arcs -ftest-coverage"
  - export USR_LFLAGS+="-mcmodel=medium"

