language: fortran

notifications:
  email:
    on_success: change
    on_failure: always

sudo: required

env:
  matrix:
    - TEST=GRAMMIAN_UNIT
    - TEST=BAFF_COMP
    - TEST=BAF_COMP
    - TEST=BAF_INTEG

before_install: 
  - export ROOT_DIR=$(pwd -P)

  # Install MPICH
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich

  # Set up Nek5000
  - git clone --single-branch -b presolve-fix https://github.com/kent0/Nek5000
  - export SOURCE_ROOT=$ROOT_DIR/Nek5000
  - (cd Nek5000/tools; ./maketools genmap)

before_script:
  - export FC=mpif77
  - export CC=mpicc
  - export FFLAGS="-w"

script: $ROOT_DIR/tests/test.sh
