#!/bin/bash -x

cd $ROOT_DIR/bin
./gsnaps baf

cd $ROOT_DIR/cases/baf
git clean -dfx . &> /dev/null

ls $ROOT_DIR/data/baf | sed 's/^/..\/..\/data\/baf\//g' > file.list

$ROOT_DIR/bin/linkm
$SOURCE_ROOT/bin/makenek baf

grep 'Compilation successful!' compiler.out &> /dev/null
comp_code="$?"
echo "comp_code=$comp_code"

$SOURCE_ROOT/bin/genmap > /dev/null << Z
baf
.01
Z

echo baf       >  SESSION.NAME
echo `pwd`'/' >>  SESSION.NAME
mpiexec -np 1 ./nek5000 | tee logfile

ic_code=$(grep 'ic_test' logfile | awk '{print $1}')
echo "ic_code=$ic_code"

grep 'run successful: dying ...' logfile &> /dev/null
success_code="$?"
echo "success_code=$success_code"

exit $((comp_code+ic_code+success_code))
