#!/bin/bash -x

mkdir $ROOT_DIR/data
cd $ROOT_DIR/data
wget -O baf.tar.gz baf https://uofi.box.com/shared/static/dzkax0ftzplzo1fh7zsijzttwws7iomj.gz
tar -xvzf baf.tar.gz &> /dev/null

cd $ROOT_DIR/cases/baf
git clean -dfx .

ls $ROOT_DIR/data/baf | sed 's/^/..\/..\/data\/baf\//g' > file.list

cp "$SOURCE_ROOT/bin/makenek" .
$ROOT_DIR/bin/linkc
./makenek bafr &> /dev/null
grep 'Compilation successful!' compiler.out
comp_code="$?"
echo "comp_code=$comp_code"

$SOURCE_ROOT/bin/genmap << Z
baf
.01
Z

$SOURCE_ROOT/bin/nekmpi baf 1

ls -latr

t=$(grep 'ic_test' baf.log.1)
ic_code=$(awk '{print $1}' $t)
echo "ic_code=$ic_code"

grep 'run successful: dying ...' baf.log.1
success_code="$?"
echo "success_code=$success_code"

exit $((comp_code+ic_code+success_code))
