#!/bin/bash

mkdir $ROOT_DIR/data
cd $ROOT_DIR/data
wget -O baf.tar.gz baf https://uofi.box.com/shared/static/dzkax0ftzplzo1fh7zsijzttwws7iomj.gz
tar -xvzf baf.tar.gz

cd $ROOT_DIR/cases/baf
git clean -dfx .

ls $ROOT_DIR/data/baf | sed 's/^/..\/..\/data\/baf\//g' > file.list

cp "$SOURCE_ROOT/bin/makenek" .
$ROOT_DIR/bin/linkc
./makenek bafr &> /dev/null
grep 'Compilation successful!' compiler.out
comp_code="$?"

$SOURCE_ROOT/bin/genmap << Z
baf
.01
Z

$SOURCE_ROOT/bin/nek baf

t=$(grep ic_test baf.log.1)
ic_code=$(awk '{print $1}' $t)

grep 'run successful: dying ...' baf.log.1
success_code="$?"
