#!/bin/bash -x

# solve the stokes problem and copy the output to s0.f00001
# usage: ./stokes

tmp=`mktemp`

rea='ldc16.rea'
cp $rea $tmp

iftran=" F      IFTRAN"
ifnav="11*F    IFNAV & IFADVC (convection in P.S. fields)"

sed -i.bu "131s/.*/${iftran}/g" $rea
sed -i.bu "132s/.*/${ifnav}/g" $rea

rm nek5000
./mn ldc
nekmpi ldc16 8

cp ldc160.f00001 s0.f00001
rm ldc160.f00001

mv "$tmp" $rea
rm "${rea}.bu"
