#!/bin/bash -x

# solve the stokes problem and copy the output to s0.f00001
# usage: ./stokes

tmp=`mktemp`

rea='ldc16.rea'
cp $rea $tmp

iftran=" F         IFTRAN"
ifnav=" F, 10*F   IFNAV & IFADVC (convection in P.S. fields)"

perl -i -pe "s/.*/${iftran}/ if $.==131" $rea
perl -i -pe "s/.*/${ifnav}/ if $.==132" $rea

rm nek5000
./mn ldc
nekmpi ldc16 8

cp ldc160.f00001 s0.f00001
rm ldc160.f00001

mv "$tmp" $rea
rm "${rea}.bu"
