name: Unit

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test: [GRAMIAN, IC, A0, B0, C0]
        ips: [L2, H10]
    env:
      MOR_DIR: /home/runner/work/NekMOR/NekMOR
      USR: "ana.o aux.o conv.o dump.o ei.o filter.o lapack.o pod.o qoi.o rom.o read.o time.o const.o unit.o rk.o legacy.o mpar.o tensor.o"

    steps:
      - uses: actions/checkout@v2

      - name: Setup NekMOR
        run: |
          echo "$MOR_DIR/bin" >> $GITHUB_PATH

      - name: Install MPICH
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y libmpich-dev mpich

      - name: Check MPICH
        run: |
          type mpif77
          type mpicc

      - name: Set Flags
        run: |
          echo "FC=mpif77" >> $GITHUB_ENV
          echo "CC=mpicc" >> $GITHUB_ENV
          echo "FFLAGS=-w -mcmodel=medium -fprofile-arcs -ftest-coverage" >> $GITHUB_ENV
          echo "USR_LFLAGS=-mcmodel=medium" >> $GITHUB_ENV

      - name: Setup Nek5000
        run: |
          git clone --single-branch -b prod https://github.com/kent0/Nek5000
          echo "NEK_SOURCE_ROOT=$MOR_DIR/Nek5000" >> $GITHUB_ENV
          echo "$NEK_SOURCE_ROOT/bin" >> $GITHUB_PATH
          echo 'nek_source_root' "$NEK_SOURCE_ROOT"
          echo 'path' "$PATH"
          (cd Nek5000/tools; ./maketools genmap)

      - name: Unit Test
        run: |
          TYPE=UNIT TEST=${{ matrix.test }} IPS=${{ matrix.ips }} $MOR_DIR/tests/test.sh
